version: '3.9'
services:
  opensearch:
    build: .
    container_name: marketplace_os
    hostname: marketplace_os
    ports:
      # http://localhost:9200
      - "9200:9200"
      - "9600:9600"
    environment:
      - discovery.type=single-node
      - "DISABLE_SECURITY_PLUGIN=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards
    container_name: marketplace_os_dashboards
    ports:
      #  http://localhost:5601
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://marketplace-os:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"